services:
  - type: web
    name: michis-matematicas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
